### ISSUE TITLE
Latest Scriptreload don't work :/ 

### ISSUE THREAD

**Issue by solding** [crank015/Sinusbot-Scripts#2]
Hi! 

Your Scriptreload is the only one I found to reload scripts, and can't live without it! XD
But sinse latest sinusbot version 0.13.37 (on windows) your script don't work anymore :/ 
(tried all versions of your script)

Could you please uppdate your script / help me make one that works on version 0.13.37 on windows :)

Thanks in advance!

**Comment by Lulalaby** [comment]
Solved: https://github.com/crank015/Sinusbot-Scripts/blob/master/newest/scriptReload.js
